use_frameworks!

target 'SquircleView_Example' do
  pod 'SquircleView', :path => '../'

  target 'SquircleView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
